export const IMAGE_BASE: string = '/'
export const IMAGE_HOME: string = '/home'
export const IMAGE_ICONS: string = '/icons'
export const IMAGE_UI: string = '/ui'
export const IMAGE_PRODUCT: string = '/products'
